name: List Project Fields

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  list-fields:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.PROJECT_TOKEN }}

    steps:
      - name: List Project fields
        run: |

          echo "========================================="
          echo "CAMPOS DO PROJECT GEORURAL"
          echo "========================================="

          gh api graphql \
            -f query='
              query {
                organization(login: "SquadTech-IV") {
                  projectV2(number: 1) {

                    id
                    number
                    title

                    fields(first: 50) {
                      nodes {

                        __typename

                        ... on ProjectV2Field {
                          id
                          name
                        }

                        ... on ProjectV2SingleSelectField {
                          id
                          name
                          options {
                            id
                            name
                          }
                        }

                        ... on ProjectV2IterationField {
                          id
                          name
                        }

                      }
                    }
                  }
                }
              }
            '
